### PR TITLE
refactor: split examples

### PR DESCRIPTION
**Pull request by leosuncin**
I separated each example in its own project, so, I can add more examples later without breaking previous ones.

### CODE REVIEW

**Comment by leosuncin** [comment]
@garronej, what do you think?

**Comment by garronej** [comment]
@leosuncin I think it's great!  
Thank you very, very, much for taking the time to put together a clean demo app like that.  
I am cloning to inspect in greater details.

**Comment by garronej** [comment]
Damn, I am stupid.  
I didn't see it was a pull request.  
I don't care about the lost of my suggestion but what do you think about stacking the example in a single app like I did in my branch?  
image
I think it's cool. It demonstrate how you can have multiple usecases and keep the conmplexity in check.

**Comment by leosuncin** [comment]
It can works, but I think that's better to keep the basic examples the more simple as possible

**Comment by leosuncin** [comment]
I'm planning to add a CRUD example later

**Comment by leosuncin** [comment]
But first, I need to put in shape the current code

**Comment by garronej** [comment]
Ok fair enough. It's true that it's best to have simple examples.

**Comment by garronej** [comment]
Don't worry about my PR.  
Maybe juste review quickly is you strongly disagree with some of the changes I won't submit them again.

**Comment by leosuncin** [comment]
I changed the implementation of `createTodoApi` and removed the class.

I personally prefer to use _default export_ over _named export_ for React Components, I don't think that's make a difference which you use about anything that matter, except when you import a module and need to rename it to avoid a collision:

```typescript
import WhateverNameYouWant from './Component'
```

versus

```typescript
import { Component as WhateverNameYouWant } from './Component'
```

The first one is shorter

**Pull request merged**
